on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Checkout submodules
        run: git submodule update --init --recursive
      # install libstdc++
      - name: Install libstdc++
        run: sudo apt update && sudo apt install -y gcc-12-base libstdc++6
      # install poetry
      - name: Install poetry
        run: pipx install poetry
      # set-up python with cache
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Update pip
        run: poetry run pip install -U pip
      - name: Install requirements
        run: poetry install --no-root
      - name: Build cvxpy core
        working-directory: ./cvxpy
        run: bash rebuild_cvxcore.sh
      - name: Fixup cvxpycore import
        working-directory: ./cvxpy/cvxpy
        run: sed -i 's/from . import _cvxcore/import _cvxcore/' cvxcore/python/cvxcore.py
      - name: Compile Cython
        run: poetry run python scripts/compile_cython.py
      - name: Save commit hash
        run: echo ${{ github.sha }} >> version.txt
      - name: Compile ladder zip
        run: poetry run python scripts/create_ladder_zip.py
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq bot.zip -d out
      - uses: actions/upload-artifact@v4
        with:
          name: ladder-zip
          path: out
      - name: Upload to AIArena
        env:
          UPLOAD_API_TOKEN: ${{ secrets.UPLOAD_API_TOKEN }}
          UPLOAD_BOT_ID: ${{ secrets[format('UPLOAD_BOT_ID_{0}', github.ref_name)] }}
        run: poetry run python scripts/upload_to_ai_arena.py
